In [1]:
import numpy as np
import pandas as pd

In [13]:
df = pd.read_csv("dataset//archive//spam.csv", encoding = 'latin-1')

In [16]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [17]:
df.shape

(5572, 5)

## Data Cleaning

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str
 1   v2          5572 non-null   str
 2   Unnamed: 2  50 non-null     str
 3   Unnamed: 3  12 non-null     str
 4   Unnamed: 4  6 non-null      str
dtypes: str(5)
memory usage: 217.8 KB

In [26]:
# drop last three cols
df.drop(columns = df.columns[-3 : ].tolist(), inplace = True)

In [28]:
df.sample(5)

        v1                                                 v2
4385   ham  , im .. On the snowboarding trip. I was wonder...
1295   ham                          TELL HER I SAID EAT SHIT.
3748  spam  Dear Voucher Holder 2 claim your 1st class air...
3      ham  U dun say so early hor... U c already then say...
3166   ham  When people see my msgs, They think Iam addict...

In [29]:
# renaming the cols
df.rename(columns = {'v1' : 'target', 'v2' : 'text'}, inplace = True)

In [30]:
df.sample(5)

     target                                               text
3522    ham                                    Try neva mate!!
3914    ham             Ard 530 lor. I ok then message Ì_ lor.
1800    ham  excellent. I spent  &lt;#&gt;  years in the Ai...
1915    ham  Its not that time of the month nor mid of the ...
4255    ham  Aah! A cuddle would be lush! I'd need lots of ...

In [31]:
# label encoding of target
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [33]:
df['target'] = encoder.fit_transform(df['target'])

In [34]:
df.sample(5)

      target                                               text
950        0         Awesome, lemme know whenever you're around
47         0                    Fair enough, anything going on?
1621       0  Living is very simple.. Loving is also simple....
683        1  Hi I'm sue. I am 20 years old and work as a la...
2762       0  ARR birthday today:) i wish him to get more os...

In [36]:
# missing values
df.isnull().sum()

target    0
text      0
dtype: int64

In [38]:
# duplicated rows
df.duplicated().sum()

np.int64(403)